repos:
  # 1. Standard Community Hooks (Formatting & Safety)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
 #     - id: trailing-whitespace
 #     - id: end-of-file-fixer
      - id: check-yaml
        exclude: wedding-site-chart/templates/

  # 2. Secret Detection (Gitleaks)
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks

# 3. Static Analysis (SonarCloud)
  - repo: local
    hooks:
      - id: sonar-scanner
        name: SonarScanner (SonarCloud)
        entry: 'cmd /c "if "%SONAR_TOKEN%"=="" (echo SONAR_TOKEN is not set. Set it with: setx SONAR_TOKEN ^<token^> ^& exit /b 1) else sonar-scanner -Dsonar.token=%SONAR_TOKEN% -Dsonar.scanner.skipJreProvisioning=true -Dproject.settings=sonar-project.local.properties"'
        language: system
        pass_filenames: false
#        stages: [pre-commit]

  # 3. Local Hooks (Your custom tests)
 # - repo: local
  #  hooks:
   #   - id: npm-test
    #    name: Run Wedding Site Unit Tests
     #   entry: npm test
      #  language: system
       # pass_filenames: false
        #stages: [commit]

#      - id: image-size-check
 #       name: Block Large Images (>1MB)
  #      entry: bash -c 'find . -path ./node_modules -prune -o -type f \( -name "*.jpg" -o -name "*.png" \) -size +1M -print | grep . && exit 1 || exit 0'
   #     language: system
    #    pass_filenames: false
