apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-pushgateway
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      interval: 15s
