apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deploy"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wedding-site
  template:
    metadata:
      labels:
        app: wedding-site
    spec:
      automountServiceAccountToken: false # Clears the first SonarQube issue
      containers:
        - name: wedding-site
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
          requests:
              memory: "128Mi"
              cpu: "100m"
          limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 5000
