{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway
  labels:
    release: {{ .Values.monitoring.releaseLabel }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-pushgateway
  namespaceSelector:
    matchNames:
      - {{ .Values.monitoring.namespace }}
  endpoints:
    - port: http
      interval: 15s
{{- end }}
