replicaCount: 2

image:
  repository: europe-west2-docker.pkg.dev/testproject01-481614/wedding-site
  tag: uat-latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: false
  host: "" #not ready yet -too costly
  className: ""
  annotations: {}

monitoring:
  enabled: true
  releaseLabel: monitoring
  namespace: monitoring
